/*
 * This file is part of the Silicon Labs Arduino Core
 *
 * The MIT License (MIT)
 *
 * Copyright 2024 Silicon Laboratories Inc. www.silabs.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_TFLITE_MICRO_PRESENT
#define SL_CATALOG_APP_ASSERT_PRESENT
#define SL_CATALOG_APP_LOG_PRESENT
#define SL_CATALOG_BLUETOOTH_CONFIGURATION_PRESENT
#define SL_CATALOG_BLUETOOTH_CTE_SUPPORT_PRESENT
#define SL_CATALOG_BLUETOOTH_CS_SUPPORT_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_ADVERTISER_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_BUILTIN_BONDING_DATABASE_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_CONNECTION_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_DYNAMIC_GATTDB_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_GATT_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_GATT_SERVER_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_LEGACY_ADVERTISER_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_LEGACY_SCANNER_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_SCANNER_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_SM_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_SYSTEM_PRESENT
#define SL_CATALOG_BLUETOOTH_HOST_ADAPTATION_PRESENT
#define SL_CATALOG_BLUETOOTH_RTOS_ADAPTATION_PRESENT
#define SL_CATALOG_BLUETOOTH_PRESENT
#define SL_CATALOG_GECKO_BOOTLOADER_INTERFACE_PRESENT
#define SL_CATALOG_CLOCK_MANAGER_PRESENT
#define SL_CATALOG_CMSIS_OS_COMMON_PRESENT
#define SL_CATALOG_DEVICE_INIT_PRESENT
#define SL_CATALOG_DEVICE_INIT_CORE_PRESENT
#define SL_CATALOG_DEVICE_INIT_DCDC_PRESENT
#define SL_CATALOG_MVP_PRESENT
#define SL_CATALOG_EMLIB_CORE_PRESENT
#define SL_CATALOG_EMLIB_CORE_DEBUG_CONFIG_PRESENT
#define SL_CATALOG_EMLIB_RMU_PRESENT
#define SL_CATALOG_FREERTOS_KERNEL_PRESENT
#define SL_CATALOG_KERNEL_PRESENT
#define SL_CATALOG_GPIO_PRESENT
#define SL_CATALOG_GPIOINTERRUPT_PRESENT
#define SL_CATALOG_HFXO_MANAGER_PRESENT
#define SL_CATALOG_INTERRUPT_MANAGER_PRESENT
#define SL_CATALOG_IOSTREAM_PRESENT
#define SL_CATALOG_RETARGET_STDIO_PRESENT
#define SL_CATALOG_IOSTREAM_UART_COMMON_PRESENT
#define SL_CATALOG_IOSTREAM_USART_PRESENT
#define SL_CATALOG_MEMORY_MANAGER_PRESENT
#define SL_CATALOG_MEMORY_PROFILER_API_PRESENT
#define SL_CATALOG_MPU_PRESENT
#define SL_CATALOG_MX25_FLASH_SHUTDOWN_EUSART_PRESENT
#define SL_CATALOG_NVM3_PRESENT
#define SL_CATALOG_POWER_MANAGER_PRESENT
#define SL_CATALOG_PSA_CRYPTO_PRESENT
#define SL_CATALOG_PWM_PRESENT
#define SL_CATALOG_PWM_LED0_PRESENT
#define SL_CATALOG_RAIL_LIB_PRESENT
#define SL_CATALOG_RAIL_UTIL_PTI_PRESENT
#define SL_CATALOG_SE_MANAGER_PRESENT
#define SL_CATALOG_SL_CORE_PRESENT
#define SL_CATALOG_SLEEPTIMER_PRESENT
#define SL_CATALOG_SLI_PROTOCOL_CRYPTO_PRESENT

#endif // SL_COMPONENT_CATALOG_H
