name=Zigbee
version=5.0.0
author=Silicon Labs
maintainer=Silicon Labs <arduino@silabs.com>
sentence=Silicon Labs Zigbee library for creating Zigbee 3.0 devices.
paragraph=Create your own Zigbee smart home devices using EmberZNet on Silicon Labs hardware.
category=Communication
url=https://github.com/SiliconLabs/arduino
architectures=silabs
dot_a_linkage=false
includes=Zigbee.h
