// Generated by write_buildconfig_header.py
// From "//third_party/connectedhomeip/src/setup_payload:gen_additional_data_payload_buildconfig"

#ifndef SETUP_PAYLOAD_CHIPADDITIONALDATAPAYLOADBUILDCONFIG_H_
#define SETUP_PAYLOAD_CHIPADDITIONALDATAPAYLOADBUILDCONFIG_H_

#endif  // SETUP_PAYLOAD_CHIPADDITIONALDATAPAYLOADBUILDCONFIG_H_
