#ifndef CRYPTO_CRYPTOBUILDCONFIG_H_
#define CRYPTO_CRYPTOBUILDCONFIG_H_

#define CHIP_CRYPTO_MBEDTLS 1
#define CHIP_CRYPTO_OPENSSL 0
#define CHIP_WITH_OPENSSL 0
#define CHIP_CRYPTO_HSM 0
#define CHIP_CRYPTO_HSM_NXP 0

#endif  // CRYPTO_CRYPTOBUILDCONFIG_H_
