/*
 * This file is part of the Silicon Labs Arduino Core
 *
 * The MIT License (MIT)
 *
 * Copyright 2024 Silicon Laboratories Inc. www.silabs.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// This file is autogenerated by Simplicity Configuration Tools.
// The contents of this file will be replaced in their entirety upon regeneration.
// 
// Source template file: RTE_Components.h.jinja


#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* standard device header from emlib */
#define CMSIS_device_header        "em_device.h"

/* components are auto-generated here */

#define RTE_RTOS_FreeRTOS_CORE

#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2

#define RTE_RTOS_FreeRTOS_COROUTINE

#define RTE_RTOS_FreeRTOS_EVENTGROUPS

#define RTE_RTOS_FreeRTOS_TIMERS

#define RTE_RTOS_FreeRTOS_HEAP_3


#endif /* RTE_COMPONENTS_H */

/* This file is autogenerated by Simplicity Configuration Tools. */
/* The contents of this file will be replaced in their entirety upon regeneration. */
/*  */
/* Source template file: RTE_Components.h.jinja */

