name=Silabs BTHome v2
version=4.0.0
author=Peter Jolankai
maintainer=Silicon Labs <arduino@silabs.com>
sentence=Silicon Labs BTHome v2 library.
paragraph=Broadcast sensor data using Bluetooth Low Energy (BLE) and the BTHome v2 protocol.
category=Communication
url=https://github.com/SiliconLabs/arduino
architectures=silabs
dot_a_linkage=false
